apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubestronaut_fastapi
  name: kubestronaut_fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubestronaut_fastapi
  strategy: {}
  template:
    metadata:
      labels:
        app: kubestronaut_fastapi
    spec:
      containers:
      - image: "{{ .Values.fastapi.repository }}:{{ .Values.fastapi.tag }}"
        name: kubestronaut_fastapi
        ports:
        - containerPort: 8000
        resources: {}
status: {}
