apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubestronautfastapi
  name: kubestronautfastapi
spec:
  replicas: {{ .Values.fastapi.replicaCount }}
  selector:
    matchLabels:
      app: kubestronautfastapi
  strategy: {}
  template:
    metadata:
      labels:
        app: kubestronautfastapi
    spec:
      containers:
      - image: "{{ .Values.fastapi.repository }}:{{ .Values.fastapi.tag }}"
        name: kubestronautfastapi
        ports:
        - containerPort: 8000
        resources: {}
status: {}
