apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubestronaut_streamlit
  name: kubestronaut_streamlit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubestronaut_streamlit
  strategy: {}
  template:
    metadata:
      labels:
        app: kubestronaut_streamlit
    spec:
      containers:
      - image: "{{ .Values.streamlit.repository }}:{{ .Values.streamlit.tag }}"
        name: kubestronaut_streamlit
        ports:
        - containerPort: 8501
        resources: {}
status: {}
