---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: kubestronaut-predictor-all
  namespace: kubestronaut-predictor
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
#      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
      messageTemplate: "Image update: {{ range .Changed.Images -}}{{ .Repository }}:{{ .Tag }} {{ end }}"
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: kubestronaut-predictor-deploy
  update:
    path: ./helm/charts/kubestronaut-predictor
    strategy: Setters
